export const animals = [
  {
    location: 'Kharkiv',
    isDog: true,
    sex: 'male',
    age: 1,
    type: 'Poodle Toy',
    color: 'black',
    isVaccinated: true,
    description:
      'This is a beautiful example of a Poodle Toy, known for its Mixed coat. At 1 years old, Dog 1 is vaccinated and loves to play in Ukraine.',
    images: [
      'https://images.dog.ceo/breeds/affenpinscher/n02110627_5743.jpg',
      'https://images.dog.ceo/breeds/affenpinscher/n02110627_8250.jpg',
      'https://images.dog.ceo/breeds/african/n02116738_10493.jpg',
    ],
    name: 'Max',
    size: 'medium',
  },
  {
    location: 'Dnipro',
    isDog: false,
    sex: 'female',
    age: 2,
    type: 'Retriever Flatcoated',
    color: 'white',
    isVaccinated: false,
    description:
      'This is a beautiful example of a Retriever Flatcoated, known for its Mixed coat. At 2 years old, Dog 2 is not vaccinated and loves to play in Ukraine.',
    images: [
      'https://images.dog.ceo/breeds/affenpinscher/n02110627_5743.jpg',
      'https://images.dog.ceo/breeds/affenpinscher/n02110627_8250.jpg',
    ],
    name: 'Bella',
    size: 'big',
  },
  {
    location: 'Lviv',
    isDog: true,
    sex: 'male',
    age: 3,
    type: 'Papillon',
    color: 'white',
    isVaccinated: true,
    description:
      'This is a beautiful example of a Papillon, known for its Mixed coat. At 3 years old, Dog 3 is vaccinated and loves to play in Ukraine.',
    images: [
      'https://images.dog.ceo/breeds/african/n02116738_10493.jpg',
      'https://images.dog.ceo/breeds/african/n02116738_8719.jpg',
    ],
    name: 'Charlie',
    size: 'small',
  },
  {
    location: 'Kharkiv',
    isDog: false,
    sex: 'female',
    age: 4,
    type: 'Mastiff English',
    color: 'brown',
    isVaccinated: false,
    description:
      'This is a beautiful example of a Mastiff English, known for its Mixed coat. At 4 years old, Dog 4 is not vaccinated and loves to play in Ukraine.',
    images: [
      'https://images.dog.ceo/breeds/airedale/n02096051_4514.jpg',
      'https://images.dog.ceo/breeds/airedale/n02096051_9319.jpg',
    ],
    name: 'Luna',
    size: 'medium',
  },
  {
    location: 'Dnipro',
    isDog: true,
    sex: 'male',
    age: 5,
    type: 'Komondor',
    color: 'mixed',
    isVaccinated: true,
    description:
      'This is a beautiful example of a Komondor, known for its Mixed coat. At 5 years old, Dog 5 is vaccinated and loves to play in Ukraine.',
    images: [
      'https://images.dog.ceo/breeds/komondor/n02105505_3713.jpg',
      'https://images.dog.ceo/breeds/komondor/n02105505_3713_1.jpg',
      'https://images.dog.ceo/breeds/komondor/n02105505_3713_2.jpg',
    ],
    name: 'Cooper',
    size: 'big',
  },
  {
    location: 'Kharkiv',
    isDog: false,
    sex: 'female',
    age: 6,
    type: 'Poodle Toy',
    color: 'mixed',
    isVaccinated: false,
    description:
      'This is a beautiful example of a Poodle Toy, known for its Mixed coat. At 6 years old, Dog 6 is not vaccinated and loves to play in Ukraine.',
    images: [
      'https://images.dog.ceo/breeds/poodle-toy/n02113624_4589.jpg',
      'https://images.dog.ceo/breeds/poodle-toy/n02113624_4589_1.jpg',
      'https://images.dog.ceo/breeds/poodle-toy/n02113624_4589_2.jpg',
    ],
    name: 'Lucy',
    size: 'small',
  },
  {
    location: 'Lviv',
    isDog: true,
    sex: 'male',
    age: 7,
    type: 'Retriever Flatcoated',
    color: 'mixed',
    isVaccinated: true,
    description:
      'This is a beautiful example of a Retriever Flatcoated, known for its Mixed coat. At 7 years old, Dog 7 is vaccinated and loves to play in Ukraine.',
    images: [
      'https://images.dog.ceo/breeds/retriever-flatcoated/n02099267_3768.jpg',
      'https://images.dog.ceo/breeds/retriever-flatcoated/n02099267_3768_1.jpg',
      'https://images.dog.ceo/breeds/retriever-flatcoated/n02099267_3768_2.jpg',
    ],
    name: 'Buddy',
    size: 'medium',
  },
  {
    location: 'Kharkiv',
    isDog: false,
    sex: 'female',
    age: 8,
    type: 'Papillon',
    color: 'mixed',
    isVaccinated: false,
    description:
      'This is a beautiful example of a Papillon, known for its Mixed coat. At 8 years old, Dog 8 is not vaccinated and loves to play in Ukraine.',
    images: [
      'https://images.dog.ceo/breeds/papillon/n02086910_3769.jpg',
      'https://images.dog.ceo/breeds/papillon/n02086910_3769_1.jpg',
      'https://images.dog.ceo/breeds/papillon/n02086910_3769_2.jpg',
    ],
    name: 'Daisy',
    size: 'big',
  },
  {
    location: 'Lviv',
    isDog: true,
    sex: 'male',
    age: 9,
    type: 'Mastiff English',
    color: 'white',
    isVaccinated: true,
    description:
      'This is a beautiful example of a Mastiff English, known for its Mixed coat. At 9 years old, Dog 9 is vaccinated and loves to play in Ukraine.',
    images: [
      'https://images.dog.ceo/breeds/akita/Akita_Dog.jpg',
      'https://images.dog.ceo/breeds/akita/Akita_hiking_in_Shpella_e_Pellumbasit.jpg',
      'https://images.dog.ceo/breeds/akita/Japaneseakita.jpg',
    ],
    name: 'Rocky',
    size: 'small',
  },
  {
    location: 'Kiev',
    isDog: false,
    sex: 'female',
    age: 10,
    type: 'Komondor',
    color: 'black',
    isVaccinated: false,
    description:
      'This is a beautiful example of a Komondor, known for its Mixed coat. At 10 years old, Dog 10 is not vaccinated and loves to play in Ukraine.',
    images: [
      'https://images.dog.ceo/breeds/komondor/n02105505_3713.jpg',
      'https://images.dog.ceo/breeds/komondor/n02105505_3713_1.jpg',
      'https://images.dog.ceo/breeds/komondor/n02105505_3713_2.jpg',
    ],
    name: 'Molly',
    size: 'medium',
  },
  {
    location: 'Dnipro',
    isDog: true,
    sex: 'male',
    age: 1,
    type: 'Poodle Toy',
    color: 'brown',
    isVaccinated: true,
    description:
      'This is a beautiful example of a Poodle Toy, known for its Mixed coat. At 1 years old, Dog 11 is vaccinated and loves to play in Ukraine.',
    images: [
      'https://images.dog.ceo/breeds/poodle-toy/n02113624_4589.jpg',
      'https://images.dog.ceo/breeds/poodle-toy/n02113624_4589_1.jpg',
      'https://images.dog.ceo/breeds/poodle-toy/n02113624_4589_2.jpg',
    ],
    name: 'Bear',
    size: 'big',
  },
  {
    location: 'Kharkiv',
    isDog: false,
    sex: 'female',
    age: 2,
    type: 'Retriever Flatcoated',
    color: 'brown',
    isVaccinated: false,
    description:
      'This is a beautiful example of a Retriever Flatcoated, known for its Mixed coat. At 2 years old, Dog 12 is not vaccinated and loves to play in Ukraine.',
    images: [
      'https://images.dog.ceo/breeds/retriever-flatcoated/n02099267_3768.jpg',
      'https://images.dog.ceo/breeds/retriever-flatcoated/n02099267_3768_1.jpg',
      'https://images.dog.ceo/breeds/retriever-flatcoated/n02099267_3768_2.jpg',
    ],
    name: 'Sadie',
    size: 'small',
  },
  {
    location: 'Dnipro',
    isDog: true,
    sex: 'male',
    age: 3,
    type: 'Papillon',
    color: 'white',
    isVaccinated: true,
    description:
      'This is a beautiful example of a Papillon, known for its Mixed coat. At 3 years old, Dog 13 is vaccinated and loves to play in Ukraine.',
    images: [
      'https://images.dog.ceo/breeds/papillon/n02086910_3769.jpg',
      'https://images.dog.ceo/breeds/papillon/n02086910_3769_1.jpg',
      'https://images.dog.ceo/breeds/papillon/n02086910_3769_2.jpg',
    ],
    name: 'Tucker',
    size: 'medium',
  },
  {
    location: 'Dnipro',
    isDog: false,
    sex: 'female',
    age: 4,
    type: 'Mastiff English',
    color: 'brown',
    isVaccinated: false,
    description:
      'This is a beautiful example of a Mastiff English, known for its Mixed coat. At 4 years old, Dog 14 is not vaccinated and loves to play in Ukraine.',
    images: [
      'https://images.dog.ceo/breeds/mastiff-english/1.jpg',
      'https://images.dog.ceo/breeds/mastiff-english/1_1.jpg',
      'https://images.dog.ceo/breeds/mastiff-english/1_2.jpg',
    ],
    name: 'Maggie',
    size: 'big',
  },
  {
    location: 'Lviv',
    isDog: true,
    sex: 'male',
    age: 5,
    type: 'Komondor',
    color: 'brown',
    isVaccinated: true,
    description:
      'This is a beautiful example of a Komondor, known for its Mixed coat. At 5 years old, Dog 15 is vaccinated and loves to play in Ukraine.',
    images: [
      'https://images.dog.ceo/breeds/poodle-toy/n02113624_2244.jpg',
      'https://images.dog.ceo/breeds/poodle-toy/n02113624_2508.jpg',
      'https://images.dog.ceo/breeds/poodle-toy/n02113624_3061.jpg',
      'https://images.dog.ceo/breeds/poodle-toy/n02113624_4589.jpg',
      'https://images.dog.ceo/breeds/poodle-toy/n02113624_6684.jpg',
      'https://images.dog.ceo/breeds/poodle-toy/n02113624_7986.jpg',
    ],
    name: 'Oliver',
    size: 'small',
  },
  {
    location: 'Kiev',
    isDog: false,
    sex: 'female',
    age: 6,
    type: 'Poodle Toy',
    color: 'black',
    isVaccinated: false,
    description:
      'This is a beautiful example of a Poodle Toy, known for its Mixed coat. At 6 years old, Dog 16 is not vaccinated and loves to play in Ukraine.',
    images: [
      'https://images.dog.ceo/breeds/poodle-toy/n02113624_4589.jpg',
      'https://images.dog.ceo/breeds/poodle-toy/n02113624_4589_1.jpg',
      'https://images.dog.ceo/breeds/poodle-toy/n02113624_4589_2.jpg',
    ],
    name: 'Sophie',
    size: 'medium',
  },
  {
    location: 'Dnipro',
    isDog: true,
    sex: 'male',
    age: 7,
    type: 'Retriever Flatcoated',
    color: 'mixed',
    isVaccinated: true,
    description:
      'This is a beautiful example of a Retriever Flatcoated, known for its Mixed coat. At 7 years old, Dog 17 is vaccinated and loves to play in Ukraine.',
    images: [
      'https://images.dog.ceo/breeds/retriever-flatcoated/n02099267_3768.jpg',
      'https://images.dog.ceo/breeds/retriever-flatcoated/n02099267_3768_1.jpg',
      'https://images.dog.ceo/breeds/retriever-flatcoated/n02099267_3768_2.jpg',
    ],
    name: 'Duke',
    size: 'big',
  },
  {
    location: 'Lviv',
    isDog: false,
    sex: 'female',
    age: 8,
    type: 'Papillon',
    color: 'brown',
    isVaccinated: false,
    description:
      'This is a beautiful example of a Papillon, known for its Mixed coat. At 8 years old, Dog 18 is not vaccinated and loves to play in Ukraine.',
    images: [
      'https://images.dog.ceo/breeds/papillon/n02086910_3769.jpg',
      'https://images.dog.ceo/breeds/papillon/n02086910_3769_1.jpg',
      'https://images.dog.ceo/breeds/papillon/n02086910_3769_2.jpg',
    ],
    name: 'Chloe',
    size: 'small',
  },
  {
    location: 'Lviv',
    isDog: true,
    sex: 'male',
    age: 9,
    type: 'Mastiff English',
    color: 'mixed',
    isVaccinated: true,
    description:
      'This is a beautiful example of a Mastiff English, known for its Mixed coat. At 9 years old, Dog 19 is vaccinated and loves to play in Ukraine.',
    images: [
      'https://images.dog.ceo/breeds/mastiff-english/1.jpg',
      'https://images.dog.ceo/breeds/mastiff-english/1_1.jpg',
      'https://images.dog.ceo/breeds/mastiff-english/1_2.jpg',
    ],
    name: 'Riley',
    size: 'medium',
  },
  {
    location: 'Dnipro',
    isDog: false,
    sex: 'female',
    age: 10,
    type: 'Komondor',
    color: 'brown',
    isVaccinated: false,
    description:
      'This is a beautiful example of a Komondor, known for its Mixed coat. At 10 years old, Dog 20 is not vaccinated and loves to play in Ukraine.',
    images: [
      'https://images.dog.ceo/breeds/komondor/n02105505_3713.jpg',
      'https://images.dog.ceo/breeds/komondor/n02105505_3713_1.jpg',
      'https://images.dog.ceo/breeds/komondor/n02105505_3713_2.jpg',
    ],
    name: 'Bailey',
    size: 'big',
  },
  {
    location: 'Dnipro',
    isDog: true,
    sex: 'male',
    age: 1,
    type: 'Poodle Toy',
    color: 'brown',
    isVaccinated: true,
    description:
      'This is a beautiful example of a Poodle Toy, known for its Mixed coat. At 1 years old, Dog 21 is vaccinated and loves to play in Ukraine.',
    images: [
      'https://images.dog.ceo/breeds/poodle-toy/n02113624_4589.jpg',
      'https://images.dog.ceo/breeds/poodle-toy/n02113624_4589_1.jpg',
      'https://images.dog.ceo/breeds/poodle-toy/n02113624_4589_2.jpg',
    ],
    name: 'Toby',
    size: 'small',
  },
  {
    location: 'Lviv',
    isDog: false,
    sex: 'female',
    age: 2,
    type: 'Retriever Flatcoated',
    color: 'white',
    isVaccinated: false,
    description:
      'This is a beautiful example of a Retriever Flatcoated, known for its Mixed coat. At 2 years old, Dog 22 is not vaccinated and loves to play in Ukraine.',
    images: [
      'https://images.dog.ceo/breeds/retriever-flatcoated/n02099267_3768.jpg',
      'https://images.dog.ceo/breeds/retriever-flatcoated/n02099267_3768_1.jpg',
      'https://images.dog.ceo/breeds/retriever-flatcoated/n02099267_3768_2.jpg',
    ],
    name: 'Lola',
    size: 'medium',
  },
  {
    location: 'Lviv',
    isDog: true,
    sex: 'male',
    age: 3,
    type: 'Papillon',
    color: 'white',
    isVaccinated: true,
    description:
      'This is a beautiful example of a Papillon, known for its Mixed coat. At 3 years old, Dog 23 is vaccinated and loves to play in Ukraine.',
    images: [
      'https://images.dog.ceo/breeds/papillon/n02086910_3769.jpg',
      'https://images.dog.ceo/breeds/papillon/n02086910_3769_1.jpg',
      'https://images.dog.ceo/breeds/papillon/n02086910_3769_2.jpg',
    ],
    name: 'Jack',
    size: 'big',
  },
  {
    location: 'Lviv',
    isDog: false,
    sex: 'female',
    age: 4,
    type: 'Mastiff English',
    color: 'brown',
    isVaccinated: false,
    description:
      'This is a beautiful example of a Mastiff English, known for its Mixed coat. At 4 years old, Dog 24 is not vaccinated and loves to play in Ukraine.',
    images: [
      'https://images.dog.ceo/breeds/mastiff-english/1.jpg',
      'https://images.dog.ceo/breeds/mastiff-english/1_1.jpg',
      'https://images.dog.ceo/breeds/mastiff-english/1_2.jpg',
    ],
    name: 'Stella',
    size: 'small',
  },
  {
    location: 'Kiev',
    isDog: true,
    sex: 'male',
    age: 5,
    type: 'Komondor',
    color: 'brown',
    isVaccinated: true,
    description:
      'This is a beautiful example of a Komondor, known for its Mixed coat. At 5 years old, Dog 25 is vaccinated and loves to play in Ukraine.',
    images: [
      'https://images.dog.ceo/breeds/komondor/n02105505_3713.jpg',
      'https://images.dog.ceo/breeds/komondor/n02105505_3713_1.jpg',
      'https://images.dog.ceo/breeds/komondor/n02105505_3713_2.jpg',
    ],
    name: 'Finn',
    size: 'medium',
  },
  {
    location: 'Kiev',
    isDog: false,
    sex: 'female',
    age: 6,
    type: 'Poodle Toy',
    color: 'mixed',
    isVaccinated: false,
    description:
      'This is a beautiful example of a Poodle Toy, known for its Mixed coat. At 6 years old, Dog 26 is not vaccinated and loves to play in Ukraine.',
    images: [
      'https://images.dog.ceo/breeds/poodle-toy/n02113624_4589.jpg',
      'https://images.dog.ceo/breeds/poodle-toy/n02113624_4589_1.jpg',
      'https://images.dog.ceo/breeds/poodle-toy/n02113624_4589_2.jpg',
    ],
    name: 'Zoe',
    size: 'big',
  },
  {
    location: 'Dnipro',
    isDog: true,
    sex: 'male',
    age: 7,
    type: 'Retriever Flatcoated',
    color: 'mixed',
    isVaccinated: true,
    description:
      'This is a beautiful example of a Retriever Flatcoated, known for its Mixed coat. At 7 years old, Dog 27 is vaccinated and loves to play in Ukraine.',
    images: [
      'https://images.dog.ceo/breeds/retriever-flatcoated/n02099267_3768.jpg',
      'https://images.dog.ceo/breeds/retriever-flatcoated/n02099267_3768_1.jpg',
      'https://images.dog.ceo/breeds/retriever-flatcoated/n02099267_3768_2.jpg',
    ],
    name: 'Murphy',
    size: 'small',
  },
  {
    location: 'Kiev',
    isDog: false,
    sex: 'female',
    age: 8,
    type: 'Papillon',
    color: 'mixed',
    isVaccinated: false,
    description:
      'This is a beautiful example of a Papillon, known for its Mixed coat. At 8 years old, Dog 28 is not vaccinated and loves to play in Ukraine.',
    images: [
      'https://images.dog.ceo/breeds/borzoi/n02090622_1391.jpg',
      'https://images.dog.ceo/breeds/borzoi/n02090622_2055.jpg',
      'https://images.dog.ceo/breeds/borzoi/n02090622_6293.jpg',
      'https://images.dog.ceo/breeds/borzoi/n02090622_6449.jpg',
    ],
    name: 'Lily',
    size: 'medium',
  },
  {
    location: 'Lviv',
    isDog: true,
    sex: 'male',
    age: 9,
    type: 'Mastiff English',
    color: 'white',
    isVaccinated: true,
    description:
      'This is a beautiful example of a Mastiff English, known for its Mixed coat. At 9 years old, Dog 29 is vaccinated and loves to play in Ukraine.',
    images: [
      'https://images.dog.ceo/breeds/terrier-yorkshire/20200319_143121.jpg',
      'https://images.dog.ceo/breeds/terrier-yorkshire/n02094433_10126.jpg',
      'https://images.dog.ceo/breeds/terrier-yorkshire/n02094433_2114.jpg',
      'https://images.dog.ceo/breeds/terrier-yorkshire/n02094433_9739.jpg',
    ],
    name: 'Leo',
    size: 'big',
  },
  {
    location: 'Lviv',
    isDog: false,
    sex: 'female',
    age: 10,
    type: 'Komondor',
    color: 'brown',
    isVaccinated: false,
    description:
      'This is a beautiful example of a Komondor, known for its Mixed coat. At 10 years old, Dog 30 is not vaccinated and loves to play in Ukraine.',
    images: [
      'https://images.dog.ceo/breeds/komondor/n02105505_3713.jpg',
      'https://images.dog.ceo/breeds/komondor/n02105505_3713_1.jpg',
      'https://images.dog.ceo/breeds/komondor/n02105505_3713_2.jpg',
    ],
    name: 'Ellie',
    size: 'small',
  },
  {
    location: 'Dnipro',
    isDog: true,
    sex: 'male',
    age: 1,
    type: 'Poodle Toy',
    color: 'mixed',
    isVaccinated: true,
    description:
      'This is a beautiful example of a Poodle Toy, known for its Mixed coat. At 1 years old, Dog 31 is vaccinated and loves to play in Ukraine.',
    images: [
      'https://images.dog.ceo/breeds/poodle-toy/n02113624_4589.jpg',
      'https://images.dog.ceo/breeds/poodle-toy/n02113624_4589_1.jpg',
      'https://images.dog.ceo/breeds/poodle-toy/n02113624_4589_2.jpg',
    ],
    name: 'Gus',
    size: 'medium',
  },
  {
    location: 'Lviv',
    isDog: false,
    sex: 'female',
    age: 2,
    type: 'Retriever Flatcoated',
    color: 'black',
    isVaccinated: false,
    description:
      'This is a beautiful example of a Retriever Flatcoated, known for its Mixed coat. At 2 years old, Dog 32 is not vaccinated and loves to play in Ukraine.',
    images: [
      'https://images.dog.ceo/breeds/retriever-flatcoated/n02099267_3768.jpg',
      'https://images.dog.ceo/breeds/retriever-flatcoated/n02099267_3768_1.jpg',
      'https://images.dog.ceo/breeds/retriever-flatcoated/n02099267_3768_2.jpg',
    ],
    name: 'Nala',
    size: 'big',
  },
  {
    location: 'Kiev',
    isDog: true,
    sex: 'male',
    age: 3,
    type: 'Papillon',
    color: 'brown',
    isVaccinated: true,
    description:
      'This is a beautiful example of a Papillon, known for its Mixed coat. At 3 years old, Dog 33 is vaccinated and loves to play in Ukraine.',
    images: [
      'https://images.dog.ceo/breeds/papillon/n02086910_3769.jpg',
      'https://images.dog.ceo/breeds/papillon/n02086910_3769_1.jpg',
      'https://images.dog.ceo/breeds/papillon/n02086910_3769_2.jpg',
    ],
    name: 'Hank',
    size: 'small',
  },
  {
    location: 'Kharkiv',
    isDog: false,
    sex: 'female',
    age: 4,
    type: 'Mastiff English',
    color: 'mixed',
    isVaccinated: false,
    description:
      'This is a beautiful example of a Mastiff English, known for its Mixed coat. At 4 years old, Dog 34 is not vaccinated and loves to play in Ukraine.',
    images: [
      'https://images.dog.ceo/breeds/mastiff-english/1.jpg',
      'https://images.dog.ceo/breeds/mastiff-english/1_1.jpg',
      'https://images.dog.ceo/breeds/mastiff-english/1_2.jpg',
    ],
    name: 'Penny',
    size: 'medium',
  },
  {
    location: 'Dnipro',
    isDog: true,
    sex: 'male',
    age: 5,
    type: 'Komondor',
    color: 'mixed',
    isVaccinated: true,
    description:
      'This is a beautiful example of a Komondor, known for its Mixed coat. At 5 years old, Dog 35 is vaccinated and loves to play in Ukraine.',
    images: [
      'https://images.dog.ceo/breeds/komondor/n02105505_3713.jpg',
      'https://images.dog.ceo/breeds/komondor/n02105505_3713_1.jpg',
      'https://images.dog.ceo/breeds/komondor/n02105505_3713_2.jpg',
    ],
    name: 'Milo',
    size: 'big',
  },
  {
    location: 'Kiev',
    isDog: false,
    sex: 'female',
    age: 6,
    type: 'Poodle Toy',
    color: 'brown',
    isVaccinated: false,
    description:
      'This is a beautiful example of a Poodle Toy, known for its Mixed coat. At 6 years old, Dog 36 is not vaccinated and loves to play in Ukraine.',
    images: [
      'https://images.dog.ceo/breeds/poodle-toy/n02113624_4589.jpg',
      'https://images.dog.ceo/breeds/poodle-toy/n02113624_4589_1.jpg',
      'https://images.dog.ceo/breeds/poodle-toy/n02113624_4589_2.jpg',
    ],
    name: 'Ruby',
    size: 'small',
  },
  {
    location: 'Lviv',
    isDog: true,
    sex: 'male',
    age: 7,
    type: 'Retriever Flatcoated',
    color: 'mixed',
    isVaccinated: true,
    description:
      'This is a beautiful example of a Retriever Flatcoated, known for its Mixed coat. At 7 years old, Dog 37 is vaccinated and loves to play in Ukraine.',
    images: [
      'https://images.dog.ceo/breeds/retriever-flatcoated/n02099267_3768.jpg',
      'https://images.dog.ceo/breeds/retriever-flatcoated/n02099267_3768_1.jpg',
      'https://images.dog.ceo/breeds/retriever-flatcoated/n02099267_3768_2.jpg',
    ],
    name: 'Zeus',
    size: 'medium',
  },
  {
    location: 'Lviv',
    isDog: false,
    sex: 'female',
    age: 8,
    type: 'Papillon',
    color: 'brown',
    isVaccinated: false,
    description:
      'This is a beautiful example of a Papillon, known for its Mixed coat. At 8 years old, Dog 38 is not vaccinated and loves to play in Ukraine.',
    images: [
      'https://images.dog.ceo/breeds/papillon/n02086910_3769.jpg',
      'https://images.dog.ceo/breeds/papillon/n02086910_3769_1.jpg',
      'https://images.dog.ceo/breeds/papillon/n02086910_3769_2.jpg',
    ],
    name: 'Rosie',
    size: 'big',
  },
  {
    location: 'Dnipro',
    isDog: true,
    sex: 'male',
    age: 9,
    type: 'Mastiff English',
    color: 'mixed',
    isVaccinated: true,
    description:
      'This is a beautiful example of a Mastiff English, known for its Mixed coat. At 9 years old, Dog 39 is vaccinated and loves to play in Ukraine.',
    images: [
      'https://images.dog.ceo/breeds/mastiff-english/1.jpg',
      'https://images.dog.ceo/breeds/mastiff-english/1_1.jpg',
      'https://images.dog.ceo/breeds/mastiff-english/1_2.jpg',
    ],
    name: 'Louie',
    size: 'small',
  },
  {
    location: 'Kiev',
    isDog: false,
    sex: 'female',
    age: 10,
    type: 'Komondor',
    color: 'white',
    isVaccinated: false,
    description:
      'This is a beautiful example of a Komondor, known for its Mixed coat. At 10 years old, Dog 40 is not vaccinated and loves to play in Ukraine.',
    images: [
      'https://images.dog.ceo/breeds/komondor/n02105505_3713.jpg',
      'https://images.dog.ceo/breeds/komondor/n02105505_3713_1.jpg',
      'https://images.dog.ceo/breeds/komondor/n02105505_3713_2.jpg',
    ],
    name: 'Mia',
    size: 'medium',
  },
  {
    location: 'Kiev',
    isDog: true,
    sex: 'male',
    age: 1,
    type: 'Poodle Toy',
    color: 'brown',
    isVaccinated: true,
    description:
      'This is a beautiful example of a Poodle Toy, known for its Mixed coat. At 1 years old, Dog 41 is vaccinated and loves to play in Ukraine.',
    images: [
      'https://images.dog.ceo/breeds/poodle-toy/n02113624_4589.jpg',
      'https://images.dog.ceo/breeds/poodle-toy/n02113624_4589_1.jpg',
      'https://images.dog.ceo/breeds/poodle-toy/n02113624_4589_2.jpg',
    ],
    name: 'Jasper',
    size: 'big',
  },
  {
    location: 'Dnipro',
    isDog: false,
    sex: 'female',
    age: 2,
    type: 'Retriever Flatcoated',
    color: 'white',
    isVaccinated: false,
    description:
      'This is a beautiful example of a Retriever Flatcoated, known for its Mixed coat. At 2 years old, Dog 42 is not vaccinated and loves to play in Ukraine.',
    images: [
      'https://images.dog.ceo/breeds/retriever-flatcoated/n02099267_3768.jpg',
      'https://images.dog.ceo/breeds/retriever-flatcoated/n02099267_3768_1.jpg',
      'https://images.dog.ceo/breeds/retriever-flatcoated/n02099267_3768_2.jpg',
    ],
    name: 'Roxy',
    size: 'small',
  },
  {
    location: 'Lviv',
    isDog: true,
    sex: 'male',
    age: 3,
    type: 'Papillon',
    color: 'brown',
    isVaccinated: true,
    description:
      'This is a beautiful example of a Papillon, known for its Mixed coat. At 3 years old, Dog 43 is vaccinated and loves to play in Ukraine.',
    images: [
      'https://images.dog.ceo/breeds/papillon/n02086910_3769.jpg',
      'https://images.dog.ceo/breeds/papillon/n02086910_3769_1.jpg',
      'https://images.dog.ceo/breeds/papillon/n02086910_3769_2.jpg',
    ],
    name: 'Oscar',
    size: 'medium',
  },
  {
    location: 'Kharkiv',
    isDog: false,
    sex: 'female',
    age: 4,
    type: 'Mastiff English',
    color: 'brown',
    isVaccinated: false,
    description:
      'This is a beautiful example of a Mastiff English, known for its Mixed coat. At 4 years old, Dog 44 is not vaccinated and loves to play in Ukraine.',
    images: [
      'https://images.dog.ceo/breeds/mastiff-english/1.jpg',
      'https://images.dog.ceo/breeds/mastiff-english/1_1.jpg',
      'https://images.dog.ceo/breeds/mastiff-english/1_2.jpg',
    ],
    name: 'Gracie',
    size: 'big',
  },
  {
    location: 'Lviv',
    isDog: true,
    sex: 'male',
    age: 5,
    type: 'Komondor',
    color: 'mixed',
    isVaccinated: true,
    description:
      'This is a beautiful example of a Komondor, known for its Mixed coat. At 5 years old, Dog 45 is vaccinated and loves to play in Ukraine.',
    images: [
      'https://images.dog.ceo/breeds/komondor/n02105505_3713.jpg',
      'https://images.dog.ceo/breeds/komondor/n02105505_3713_1.jpg',
      'https://images.dog.ceo/breeds/komondor/n02105505_3713_2.jpg',
    ],
    name: 'Winston',
    size: 'small',
  },
  {
    location: 'Lviv',
    isDog: false,
    sex: 'female',
    age: 6,
    type: 'Poodle Toy',
    color: 'brown',
    isVaccinated: false,
    description:
      'This is a beautiful example of a Poodle Toy, known for its Mixed coat. At 6 years old, Dog 46 is not vaccinated and loves to play in Ukraine.',
    images: [
      'https://images.dog.ceo/breeds/poodle-toy/n02113624_4589.jpg',
      'https://images.dog.ceo/breeds/poodle-toy/n02113624_4589_1.jpg',
      'https://images.dog.ceo/breeds/poodle-toy/n02113624_4589_2.jpg',
    ],
    name: 'Coco',
    size: 'medium',
  },
  {
    location: 'Lviv',
    isDog: true,
    sex: 'male',
    age: 7,
    type: 'Retriever Flatcoated',
    color: 'brown',
    isVaccinated: true,
    description:
      'This is a beautiful example of a Retriever Flatcoated, known for its Mixed coat. At 7 years old, Dog 47 is vaccinated and loves to play in Ukraine.',
    images: [
      'https://images.dog.ceo/breeds/retriever-flatcoated/n02099267_3768.jpg',
      'https://images.dog.ceo/breeds/retriever-flatcoated/n02099267_3768_1.jpg',
      'https://images.dog.ceo/breeds/retriever-flatcoated/n02099267_3768_2.jpg',
    ],
    name: 'Sammy',
    size: 'big',
  },
  {
    location: 'Kiev',
    isDog: false,
    sex: 'female',
    age: 8,
    type: 'Papillon',
    color: 'black',
    isVaccinated: false,
    description:
      'This is a beautiful example of a Papillon, known for its Mixed coat. At 8 years old, Dog 48 is not vaccinated and loves to play in Ukraine.',
    images: [
      'https://images.dog.ceo/breeds/papillon/n02086910_3769.jpg',
      'https://images.dog.ceo/breeds/papillon/n02086910_3769_1.jpg',
      'https://images.dog.ceo/breeds/papillon/n02086910_3769_2.jpg',
    ],
    name: 'Lulu',
    size: 'small',
  },
  {
    location: 'Lviv',
    isDog: true,
    sex: 'male',
    age: 9,
    type: 'Mastiff English',
    color: 'black',
    isVaccinated: true,
    description:
      'This is a beautiful example of a Mastiff English, known for its Mixed coat. At 9 years old, Dog 49 is vaccinated and loves to play in Ukraine.',
    images: [
      'https://images.dog.ceo/breeds/springer-english/n02102040_1983.jpg',
      'https://images.dog.ceo/breeds/springer-english/n02102040_2481.jpg',
      'https://images.dog.ceo/breeds/springer-english/n02102040_3335.jpg',
      'https://images.dog.ceo/breeds/springer-english/n02102040_3693.jpg',
      'https://images.dog.ceo/breeds/springer-english/n02102040_3974.jpg',
    ],
    name: 'Teddy',
    size: 'medium',
  },
  {
    location: 'Kharkiv',
    isDog: false,
    sex: 'female',
    age: 10,
    type: 'Komondor',
    color: 'black',
    isVaccinated: false,
    description:
      'This is a beautiful example of a Komondor, known for its Mixed coat. At 10 years old, Dog 50 is not vaccinated and loves to play in Ukraine.',
    images: [
      'https://images.dog.ceo/breeds/basenji/n02110806_4302.jpg',
      'https://images.dog.ceo/breeds/basenji/n02110806_4488.jpg',
    ],
    name: 'Piper',
    size: 'big',
  },
];
