export const animals = [
  {
    location: 'Ukraine',
    isDog: true,
    sex: 'male',
    age: 1,
    type: 'Poodle Toy',
    color: 'Mixed',
    isVaccinated: true,
    description:
      'This is a beautiful example of a Poodle Toy, known for its Mixed coat. At 1 years old, Dog 1 is vaccinated and loves to play in Ukraine.',
    images: [
      'https://images.dog.ceo/breeds/affenpinscher/n02110627_5743.jpg',
      'https://images.dog.ceo/breeds/affenpinscher/n02110627_8250.jpg',
      'https://images.dog.ceo/breeds/african/n02116738_10493.jpg',
    ],
    name: 'Dog 1',
  },
  {
    location: 'Ukraine',
    isDog: true,
    sex: 'female',
    age: 2,
    type: 'Retriever Flatcoated',
    color: 'Mixed',
    isVaccinated: false,
    description:
      'This is a beautiful example of a Retriever Flatcoated, known for its Mixed coat. At 2 years old, Dog 2 is not vaccinated and loves to play in Ukraine.',
    images: [
      'https://images.dog.ceo/breeds/affenpinscher/n02110627_5743.jpg',
      'https://images.dog.ceo/breeds/affenpinscher/n02110627_8250.jpg',
    ],
    name: 'Dog 2',
  },
  {
    location: 'Ukraine',
    isDog: true,
    sex: 'male',
    age: 3,
    type: 'Papillon',
    color: 'Mixed',
    isVaccinated: true,
    description:
      'This is a beautiful example of a Papillon, known for its Mixed coat. At 3 years old, Dog 3 is vaccinated and loves to play in Ukraine.',
    images: [
      'https://images.dog.ceo/breeds/african/n02116738_10493.jpg',
      'https://images.dog.ceo/breeds/african/n02116738_8719.jpg',
    ],
    name: 'Dog 3',
  },
  {
    location: 'Ukraine',
    isDog: true,
    sex: 'female',
    age: 4,
    type: 'Mastiff English',
    color: 'Mixed',
    isVaccinated: false,
    description:
      'This is a beautiful example of a Mastiff English, known for its Mixed coat. At 4 years old, Dog 4 is not vaccinated and loves to play in Ukraine.',
    images: [
      'https://images.dog.ceo/breeds/airedale/n02096051_4514.jpg',
      'https://images.dog.ceo/breeds/airedale/n02096051_9319.jpg',
    ],
    name: 'Dog 4',
  },
  {
    location: 'Ukraine',
    isDog: true,
    sex: 'male',
    age: 5,
    type: 'Komondor',
    color: 'Mixed',
    isVaccinated: true,
    description:
      'This is a beautiful example of a Komondor, known for its Mixed coat. At 5 years old, Dog 5 is vaccinated and loves to play in Ukraine.',
    images: [
      'https://images.dog.ceo/breeds/komondor/n02105505_3713.jpg',
      'https://images.dog.ceo/breeds/komondor/n02105505_3713_1.jpg',
      'https://images.dog.ceo/breeds/komondor/n02105505_3713_2.jpg',
    ],
    name: 'Dog 5',
  },
  {
    location: 'Ukraine',
    isDog: true,
    sex: 'female',
    age: 6,
    type: 'Poodle Toy',
    color: 'Mixed',
    isVaccinated: false,
    description:
      'This is a beautiful example of a Poodle Toy, known for its Mixed coat. At 6 years old, Dog 6 is not vaccinated and loves to play in Ukraine.',
    images: [
      'https://images.dog.ceo/breeds/poodle-toy/n02113624_4589.jpg',
      'https://images.dog.ceo/breeds/poodle-toy/n02113624_4589_1.jpg',
      'https://images.dog.ceo/breeds/poodle-toy/n02113624_4589_2.jpg',
    ],
    name: 'Dog 6',
  },
  {
    location: 'Ukraine',
    isDog: true,
    sex: 'male',
    age: 7,
    type: 'Retriever Flatcoated',
    color: 'Mixed',
    isVaccinated: true,
    description:
      'This is a beautiful example of a Retriever Flatcoated, known for its Mixed coat. At 7 years old, Dog 7 is vaccinated and loves to play in Ukraine.',
    images: [
      'https://images.dog.ceo/breeds/retriever-flatcoated/n02099267_3768.jpg',
      'https://images.dog.ceo/breeds/retriever-flatcoated/n02099267_3768_1.jpg',
      'https://images.dog.ceo/breeds/retriever-flatcoated/n02099267_3768_2.jpg',
    ],
    name: 'Dog 7',
  },
  {
    location: 'Ukraine',
    isDog: true,
    sex: 'female',
    age: 8,
    type: 'Papillon',
    color: 'Mixed',
    isVaccinated: false,
    description:
      'This is a beautiful example of a Papillon, known for its Mixed coat. At 8 years old, Dog 8 is not vaccinated and loves to play in Ukraine.',
    images: [
      'https://images.dog.ceo/breeds/papillon/n02086910_3769.jpg',
      'https://images.dog.ceo/breeds/papillon/n02086910_3769_1.jpg',
      'https://images.dog.ceo/breeds/papillon/n02086910_3769_2.jpg',
    ],
    name: 'Dog 8',
  },
  {
    location: 'Ukraine',
    isDog: true,
    sex: 'male',
    age: 9,
    type: 'Mastiff English',
    color: 'Mixed',
    isVaccinated: true,
    description:
      'This is a beautiful example of a Mastiff English, known for its Mixed coat. At 9 years old, Dog 9 is vaccinated and loves to play in Ukraine.',
    images: [
      'https://images.dog.ceo/breeds/akita/Akita_Dog.jpg',
      'https://images.dog.ceo/breeds/akita/Akita_hiking_in_Shpella_e_Pellumbasit.jpg',
      'https://images.dog.ceo/breeds/akita/Japaneseakita.jpg',
    ],
    name: 'Dog 9',
  },
  {
    location: 'Ukraine',
    isDog: true,
    sex: 'female',
    age: 10,
    type: 'Komondor',
    color: 'Mixed',
    isVaccinated: false,
    description:
      'This is a beautiful example of a Komondor, known for its Mixed coat. At 10 years old, Dog 10 is not vaccinated and loves to play in Ukraine.',
    images: [
      'https://images.dog.ceo/breeds/komondor/n02105505_3713.jpg',
      'https://images.dog.ceo/breeds/komondor/n02105505_3713_1.jpg',
      'https://images.dog.ceo/breeds/komondor/n02105505_3713_2.jpg',
    ],
    name: 'Dog 10',
  },
  {
    location: 'Ukraine',
    isDog: true,
    sex: 'male',
    age: 1,
    type: 'Poodle Toy',
    color: 'Mixed',
    isVaccinated: true,
    description:
      'This is a beautiful example of a Poodle Toy, known for its Mixed coat. At 1 years old, Dog 11 is vaccinated and loves to play in Ukraine.',
    images: [
      'https://images.dog.ceo/breeds/poodle-toy/n02113624_4589.jpg',
      'https://images.dog.ceo/breeds/poodle-toy/n02113624_4589_1.jpg',
      'https://images.dog.ceo/breeds/poodle-toy/n02113624_4589_2.jpg',
    ],
    name: 'Dog 11',
  },
  {
    location: 'Ukraine',
    isDog: true,
    sex: 'female',
    age: 2,
    type: 'Retriever Flatcoated',
    color: 'Mixed',
    isVaccinated: false,
    description:
      'This is a beautiful example of a Retriever Flatcoated, known for its Mixed coat. At 2 years old, Dog 12 is not vaccinated and loves to play in Ukraine.',
    images: [
      'https://images.dog.ceo/breeds/retriever-flatcoated/n02099267_3768.jpg',
      'https://images.dog.ceo/breeds/retriever-flatcoated/n02099267_3768_1.jpg',
      'https://images.dog.ceo/breeds/retriever-flatcoated/n02099267_3768_2.jpg',
    ],
    name: 'Dog 12',
  },
  {
    location: 'Ukraine',
    isDog: true,
    sex: 'male',
    age: 3,
    type: 'Papillon',
    color: 'Mixed',
    isVaccinated: true,
    description:
      'This is a beautiful example of a Papillon, known for its Mixed coat. At 3 years old, Dog 13 is vaccinated and loves to play in Ukraine.',
    images: [
      'https://images.dog.ceo/breeds/papillon/n02086910_3769.jpg',
      'https://images.dog.ceo/breeds/papillon/n02086910_3769_1.jpg',
      'https://images.dog.ceo/breeds/papillon/n02086910_3769_2.jpg',
    ],
    name: 'Dog 13',
  },
  {
    location: 'Ukraine',
    isDog: true,
    sex: 'female',
    age: 4,
    type: 'Mastiff English',
    color: 'Mixed',
    isVaccinated: false,
    description:
      'This is a beautiful example of a Mastiff English, known for its Mixed coat. At 4 years old, Dog 14 is not vaccinated and loves to play in Ukraine.',
    images: [
      'https://images.dog.ceo/breeds/mastiff-english/1.jpg',
      'https://images.dog.ceo/breeds/mastiff-english/1_1.jpg',
      'https://images.dog.ceo/breeds/mastiff-english/1_2.jpg',
    ],
    name: 'Dog 14',
  },
  {
    location: 'Ukraine',
    isDog: true,
    sex: 'male',
    age: 5,
    type: 'Komondor',
    color: 'Mixed',
    isVaccinated: true,
    description:
      'This is a beautiful example of a Komondor, known for its Mixed coat. At 5 years old, Dog 15 is vaccinated and loves to play in Ukraine.',
    images: [
      'https://images.dog.ceo/breeds/poodle-toy/n02113624_2244.jpg',
      'https://images.dog.ceo/breeds/poodle-toy/n02113624_2508.jpg',
      'https://images.dog.ceo/breeds/poodle-toy/n02113624_3061.jpg',
      'https://images.dog.ceo/breeds/poodle-toy/n02113624_4589.jpg',
      'https://images.dog.ceo/breeds/poodle-toy/n02113624_6684.jpg',
      'https://images.dog.ceo/breeds/poodle-toy/n02113624_7986.jpg',
    ],
    name: 'Dog 15',
  },
  {
    location: 'Ukraine',
    isDog: true,
    sex: 'female',
    age: 6,
    type: 'Poodle Toy',
    color: 'Mixed',
    isVaccinated: false,
    description:
      'This is a beautiful example of a Poodle Toy, known for its Mixed coat. At 6 years old, Dog 16 is not vaccinated and loves to play in Ukraine.',
    images: [
      'https://images.dog.ceo/breeds/poodle-toy/n02113624_4589.jpg',
      'https://images.dog.ceo/breeds/poodle-toy/n02113624_4589_1.jpg',
      'https://images.dog.ceo/breeds/poodle-toy/n02113624_4589_2.jpg',
    ],
    name: 'Dog 16',
  },
  {
    location: 'Ukraine',
    isDog: true,
    sex: 'male',
    age: 7,
    type: 'Retriever Flatcoated',
    color: 'Mixed',
    isVaccinated: true,
    description:
      'This is a beautiful example of a Retriever Flatcoated, known for its Mixed coat. At 7 years old, Dog 17 is vaccinated and loves to play in Ukraine.',
    images: [
      'https://images.dog.ceo/breeds/retriever-flatcoated/n02099267_3768.jpg',
      'https://images.dog.ceo/breeds/retriever-flatcoated/n02099267_3768_1.jpg',
      'https://images.dog.ceo/breeds/retriever-flatcoated/n02099267_3768_2.jpg',
    ],
    name: 'Dog 17',
  },
  {
    location: 'Ukraine',
    isDog: true,
    sex: 'female',
    age: 8,
    type: 'Papillon',
    color: 'Mixed',
    isVaccinated: false,
    description:
      'This is a beautiful example of a Papillon, known for its Mixed coat. At 8 years old, Dog 18 is not vaccinated and loves to play in Ukraine.',
    images: [
      'https://images.dog.ceo/breeds/papillon/n02086910_3769.jpg',
      'https://images.dog.ceo/breeds/papillon/n02086910_3769_1.jpg',
      'https://images.dog.ceo/breeds/papillon/n02086910_3769_2.jpg',
    ],
    name: 'Dog 18',
  },
  {
    location: 'Ukraine',
    isDog: true,
    sex: 'male',
    age: 9,
    type: 'Mastiff English',
    color: 'Mixed',
    isVaccinated: true,
    description:
      'This is a beautiful example of a Mastiff English, known for its Mixed coat. At 9 years old, Dog 19 is vaccinated and loves to play in Ukraine.',
    images: [
      'https://images.dog.ceo/breeds/mastiff-english/1.jpg',
      'https://images.dog.ceo/breeds/mastiff-english/1_1.jpg',
      'https://images.dog.ceo/breeds/mastiff-english/1_2.jpg',
    ],
    name: 'Dog 19',
  },
  {
    location: 'Ukraine',
    isDog: true,
    sex: 'female',
    age: 10,
    type: 'Komondor',
    color: 'Mixed',
    isVaccinated: false,
    description:
      'This is a beautiful example of a Komondor, known for its Mixed coat. At 10 years old, Dog 20 is not vaccinated and loves to play in Ukraine.',
    images: [
      'https://images.dog.ceo/breeds/komondor/n02105505_3713.jpg',
      'https://images.dog.ceo/breeds/komondor/n02105505_3713_1.jpg',
      'https://images.dog.ceo/breeds/komondor/n02105505_3713_2.jpg',
    ],
    name: 'Dog 20',
  },
  {
    location: 'Ukraine',
    isDog: true,
    sex: 'male',
    age: 1,
    type: 'Poodle Toy',
    color: 'Mixed',
    isVaccinated: true,
    description:
      'This is a beautiful example of a Poodle Toy, known for its Mixed coat. At 1 years old, Dog 21 is vaccinated and loves to play in Ukraine.',
    images: [
      'https://images.dog.ceo/breeds/poodle-toy/n02113624_4589.jpg',
      'https://images.dog.ceo/breeds/poodle-toy/n02113624_4589_1.jpg',
      'https://images.dog.ceo/breeds/poodle-toy/n02113624_4589_2.jpg',
    ],
    name: 'Dog 21',
  },
  {
    location: 'Ukraine',
    isDog: true,
    sex: 'female',
    age: 2,
    type: 'Retriever Flatcoated',
    color: 'Mixed',
    isVaccinated: false,
    description:
      'This is a beautiful example of a Retriever Flatcoated, known for its Mixed coat. At 2 years old, Dog 22 is not vaccinated and loves to play in Ukraine.',
    images: [
      'https://images.dog.ceo/breeds/retriever-flatcoated/n02099267_3768.jpg',
      'https://images.dog.ceo/breeds/retriever-flatcoated/n02099267_3768_1.jpg',
      'https://images.dog.ceo/breeds/retriever-flatcoated/n02099267_3768_2.jpg',
    ],
    name: 'Dog 22',
  },
  {
    location: 'Ukraine',
    isDog: true,
    sex: 'male',
    age: 3,
    type: 'Papillon',
    color: 'Mixed',
    isVaccinated: true,
    description:
      'This is a beautiful example of a Papillon, known for its Mixed coat. At 3 years old, Dog 23 is vaccinated and loves to play in Ukraine.',
    images: [
      'https://images.dog.ceo/breeds/papillon/n02086910_3769.jpg',
      'https://images.dog.ceo/breeds/papillon/n02086910_3769_1.jpg',
      'https://images.dog.ceo/breeds/papillon/n02086910_3769_2.jpg',
    ],
    name: 'Dog 23',
  },
  {
    location: 'Ukraine',
    isDog: true,
    sex: 'female',
    age: 4,
    type: 'Mastiff English',
    color: 'Mixed',
    isVaccinated: false,
    description:
      'This is a beautiful example of a Mastiff English, known for its Mixed coat. At 4 years old, Dog 24 is not vaccinated and loves to play in Ukraine.',
    images: [
      'https://images.dog.ceo/breeds/mastiff-english/1.jpg',
      'https://images.dog.ceo/breeds/mastiff-english/1_1.jpg',
      'https://images.dog.ceo/breeds/mastiff-english/1_2.jpg',
    ],
    name: 'Dog 24',
  },
  {
    location: 'Ukraine',
    isDog: true,
    sex: 'male',
    age: 5,
    type: 'Komondor',
    color: 'Mixed',
    isVaccinated: true,
    description:
      'This is a beautiful example of a Komondor, known for its Mixed coat. At 5 years old, Dog 25 is vaccinated and loves to play in Ukraine.',
    images: [
      'https://images.dog.ceo/breeds/komondor/n02105505_3713.jpg',
      'https://images.dog.ceo/breeds/komondor/n02105505_3713_1.jpg',
      'https://images.dog.ceo/breeds/komondor/n02105505_3713_2.jpg',
    ],
    name: 'Dog 25',
  },
  {
    location: 'Ukraine',
    isDog: true,
    sex: 'female',
    age: 6,
    type: 'Poodle Toy',
    color: 'Mixed',
    isVaccinated: false,
    description:
      'This is a beautiful example of a Poodle Toy, known for its Mixed coat. At 6 years old, Dog 26 is not vaccinated and loves to play in Ukraine.',
    images: [
      'https://images.dog.ceo/breeds/poodle-toy/n02113624_4589.jpg',
      'https://images.dog.ceo/breeds/poodle-toy/n02113624_4589_1.jpg',
      'https://images.dog.ceo/breeds/poodle-toy/n02113624_4589_2.jpg',
    ],
    name: 'Dog 26',
  },
  {
    location: 'Ukraine',
    isDog: true,
    sex: 'male',
    age: 7,
    type: 'Retriever Flatcoated',
    color: 'Mixed',
    isVaccinated: true,
    description:
      'This is a beautiful example of a Retriever Flatcoated, known for its Mixed coat. At 7 years old, Dog 27 is vaccinated and loves to play in Ukraine.',
    images: [
      'https://images.dog.ceo/breeds/retriever-flatcoated/n02099267_3768.jpg',
      'https://images.dog.ceo/breeds/retriever-flatcoated/n02099267_3768_1.jpg',
      'https://images.dog.ceo/breeds/retriever-flatcoated/n02099267_3768_2.jpg',
    ],
    name: 'Dog 27',
  },
  {
    location: 'Ukraine',
    isDog: true,
    sex: 'female',
    age: 8,
    type: 'Papillon',
    color: 'Mixed',
    isVaccinated: false,
    description:
      'This is a beautiful example of a Papillon, known for its Mixed coat. At 8 years old, Dog 28 is not vaccinated and loves to play in Ukraine.',
    images: [
      'https://images.dog.ceo/breeds/borzoi/n02090622_1391.jpg',
      'https://images.dog.ceo/breeds/borzoi/n02090622_2055.jpg',
      'https://images.dog.ceo/breeds/borzoi/n02090622_6293.jpg',
      'https://images.dog.ceo/breeds/borzoi/n02090622_6449.jpg',
    ],
    name: 'Dog 28',
  },
  {
    location: 'Ukraine',
    isDog: true,
    sex: 'male',
    age: 9,
    type: 'Mastiff English',
    color: 'Mixed',
    isVaccinated: true,
    description:
      'This is a beautiful example of a Mastiff English, known for its Mixed coat. At 9 years old, Dog 29 is vaccinated and loves to play in Ukraine.',
    images: [
      'https://images.dog.ceo/breeds/terrier-yorkshire/20200319_143121.jpg',
      'https://images.dog.ceo/breeds/terrier-yorkshire/n02094433_10126.jpg',
      'https://images.dog.ceo/breeds/terrier-yorkshire/n02094433_2114.jpg',
      'https://images.dog.ceo/breeds/terrier-yorkshire/n02094433_9739.jpg',
    ],
    name: 'Dog 29',
  },
  {
    location: 'Ukraine',
    isDog: true,
    sex: 'female',
    age: 10,
    type: 'Komondor',
    color: 'Mixed',
    isVaccinated: false,
    description:
      'This is a beautiful example of a Komondor, known for its Mixed coat. At 10 years old, Dog 30 is not vaccinated and loves to play in Ukraine.',
    images: [
      'https://images.dog.ceo/breeds/komondor/n02105505_3713.jpg',
      'https://images.dog.ceo/breeds/komondor/n02105505_3713_1.jpg',
      'https://images.dog.ceo/breeds/komondor/n02105505_3713_2.jpg',
    ],
    name: 'Dog 30',
  },
  {
    location: 'Ukraine',
    isDog: true,
    sex: 'male',
    age: 1,
    type: 'Poodle Toy',
    color: 'Mixed',
    isVaccinated: true,
    description:
      'This is a beautiful example of a Poodle Toy, known for its Mixed coat. At 1 years old, Dog 31 is vaccinated and loves to play in Ukraine.',
    images: [
      'https://images.dog.ceo/breeds/poodle-toy/n02113624_4589.jpg',
      'https://images.dog.ceo/breeds/poodle-toy/n02113624_4589_1.jpg',
      'https://images.dog.ceo/breeds/poodle-toy/n02113624_4589_2.jpg',
    ],
    name: 'Dog 31',
  },
  {
    location: 'Ukraine',
    isDog: true,
    sex: 'female',
    age: 2,
    type: 'Retriever Flatcoated',
    color: 'Mixed',
    isVaccinated: false,
    description:
      'This is a beautiful example of a Retriever Flatcoated, known for its Mixed coat. At 2 years old, Dog 32 is not vaccinated and loves to play in Ukraine.',
    images: [
      'https://images.dog.ceo/breeds/retriever-flatcoated/n02099267_3768.jpg',
      'https://images.dog.ceo/breeds/retriever-flatcoated/n02099267_3768_1.jpg',
      'https://images.dog.ceo/breeds/retriever-flatcoated/n02099267_3768_2.jpg',
    ],
    name: 'Dog 32',
  },
  {
    location: 'Ukraine',
    isDog: true,
    sex: 'male',
    age: 3,
    type: 'Papillon',
    color: 'Mixed',
    isVaccinated: true,
    description:
      'This is a beautiful example of a Papillon, known for its Mixed coat. At 3 years old, Dog 33 is vaccinated and loves to play in Ukraine.',
    images: [
      'https://images.dog.ceo/breeds/papillon/n02086910_3769.jpg',
      'https://images.dog.ceo/breeds/papillon/n02086910_3769_1.jpg',
      'https://images.dog.ceo/breeds/papillon/n02086910_3769_2.jpg',
    ],
    name: 'Dog 33',
  },
  {
    location: 'Ukraine',
    isDog: true,
    sex: 'female',
    age: 4,
    type: 'Mastiff English',
    color: 'Mixed',
    isVaccinated: false,
    description:
      'This is a beautiful example of a Mastiff English, known for its Mixed coat. At 4 years old, Dog 34 is not vaccinated and loves to play in Ukraine.',
    images: [
      'https://images.dog.ceo/breeds/mastiff-english/1.jpg',
      'https://images.dog.ceo/breeds/mastiff-english/1_1.jpg',
      'https://images.dog.ceo/breeds/mastiff-english/1_2.jpg',
    ],
    name: 'Dog 34',
  },
  {
    location: 'Ukraine',
    isDog: true,
    sex: 'male',
    age: 5,
    type: 'Komondor',
    color: 'Mixed',
    isVaccinated: true,
    description:
      'This is a beautiful example of a Komondor, known for its Mixed coat. At 5 years old, Dog 35 is vaccinated and loves to play in Ukraine.',
    images: [
      'https://images.dog.ceo/breeds/komondor/n02105505_3713.jpg',
      'https://images.dog.ceo/breeds/komondor/n02105505_3713_1.jpg',
      'https://images.dog.ceo/breeds/komondor/n02105505_3713_2.jpg',
    ],
    name: 'Dog 35',
  },
  {
    location: 'Ukraine',
    isDog: true,
    sex: 'female',
    age: 6,
    type: 'Poodle Toy',
    color: 'Mixed',
    isVaccinated: false,
    description:
      'This is a beautiful example of a Poodle Toy, known for its Mixed coat. At 6 years old, Dog 36 is not vaccinated and loves to play in Ukraine.',
    images: [
      'https://images.dog.ceo/breeds/poodle-toy/n02113624_4589.jpg',
      'https://images.dog.ceo/breeds/poodle-toy/n02113624_4589_1.jpg',
      'https://images.dog.ceo/breeds/poodle-toy/n02113624_4589_2.jpg',
    ],
    name: 'Dog 36',
  },
  {
    location: 'Ukraine',
    isDog: true,
    sex: 'male',
    age: 7,
    type: 'Retriever Flatcoated',
    color: 'Mixed',
    isVaccinated: true,
    description:
      'This is a beautiful example of a Retriever Flatcoated, known for its Mixed coat. At 7 years old, Dog 37 is vaccinated and loves to play in Ukraine.',
    images: [
      'https://images.dog.ceo/breeds/retriever-flatcoated/n02099267_3768.jpg',
      'https://images.dog.ceo/breeds/retriever-flatcoated/n02099267_3768_1.jpg',
      'https://images.dog.ceo/breeds/retriever-flatcoated/n02099267_3768_2.jpg',
    ],
    name: 'Dog 37',
  },
  {
    location: 'Ukraine',
    isDog: true,
    sex: 'female',
    age: 8,
    type: 'Papillon',
    color: 'Mixed',
    isVaccinated: false,
    description:
      'This is a beautiful example of a Papillon, known for its Mixed coat. At 8 years old, Dog 38 is not vaccinated and loves to play in Ukraine.',
    images: [
      'https://images.dog.ceo/breeds/papillon/n02086910_3769.jpg',
      'https://images.dog.ceo/breeds/papillon/n02086910_3769_1.jpg',
      'https://images.dog.ceo/breeds/papillon/n02086910_3769_2.jpg',
    ],
    name: 'Dog 38',
  },
  {
    location: 'Ukraine',
    isDog: true,
    sex: 'male',
    age: 9,
    type: 'Mastiff English',
    color: 'Mixed',
    isVaccinated: true,
    description:
      'This is a beautiful example of a Mastiff English, known for its Mixed coat. At 9 years old, Dog 39 is vaccinated and loves to play in Ukraine.',
    images: [
      'https://images.dog.ceo/breeds/mastiff-english/1.jpg',
      'https://images.dog.ceo/breeds/mastiff-english/1_1.jpg',
      'https://images.dog.ceo/breeds/mastiff-english/1_2.jpg',
    ],
    name: 'Dog 39',
  },
  {
    location: 'Ukraine',
    isDog: true,
    sex: 'female',
    age: 10,
    type: 'Komondor',
    color: 'Mixed',
    isVaccinated: false,
    description:
      'This is a beautiful example of a Komondor, known for its Mixed coat. At 10 years old, Dog 40 is not vaccinated and loves to play in Ukraine.',
    images: [
      'https://images.dog.ceo/breeds/komondor/n02105505_3713.jpg',
      'https://images.dog.ceo/breeds/komondor/n02105505_3713_1.jpg',
      'https://images.dog.ceo/breeds/komondor/n02105505_3713_2.jpg',
    ],
    name: 'Dog 40',
  },
  {
    location: 'Ukraine',
    isDog: true,
    sex: 'male',
    age: 1,
    type: 'Poodle Toy',
    color: 'Mixed',
    isVaccinated: true,
    description:
      'This is a beautiful example of a Poodle Toy, known for its Mixed coat. At 1 years old, Dog 41 is vaccinated and loves to play in Ukraine.',
    images: [
      'https://images.dog.ceo/breeds/poodle-toy/n02113624_4589.jpg',
      'https://images.dog.ceo/breeds/poodle-toy/n02113624_4589_1.jpg',
      'https://images.dog.ceo/breeds/poodle-toy/n02113624_4589_2.jpg',
    ],
    name: 'Dog 41',
  },
  {
    location: 'Ukraine',
    isDog: true,
    sex: 'female',
    age: 2,
    type: 'Retriever Flatcoated',
    color: 'Mixed',
    isVaccinated: false,
    description:
      'This is a beautiful example of a Retriever Flatcoated, known for its Mixed coat. At 2 years old, Dog 42 is not vaccinated and loves to play in Ukraine.',
    images: [
      'https://images.dog.ceo/breeds/retriever-flatcoated/n02099267_3768.jpg',
      'https://images.dog.ceo/breeds/retriever-flatcoated/n02099267_3768_1.jpg',
      'https://images.dog.ceo/breeds/retriever-flatcoated/n02099267_3768_2.jpg',
    ],
    name: 'Dog 42',
  },
  {
    location: 'Ukraine',
    isDog: true,
    sex: 'male',
    age: 3,
    type: 'Papillon',
    color: 'Mixed',
    isVaccinated: true,
    description:
      'This is a beautiful example of a Papillon, known for its Mixed coat. At 3 years old, Dog 43 is vaccinated and loves to play in Ukraine.',
    images: [
      'https://images.dog.ceo/breeds/papillon/n02086910_3769.jpg',
      'https://images.dog.ceo/breeds/papillon/n02086910_3769_1.jpg',
      'https://images.dog.ceo/breeds/papillon/n02086910_3769_2.jpg',
    ],
    name: 'Dog 43',
  },
  {
    location: 'Ukraine',
    isDog: true,
    sex: 'female',
    age: 4,
    type: 'Mastiff English',
    color: 'Mixed',
    isVaccinated: false,
    description:
      'This is a beautiful example of a Mastiff English, known for its Mixed coat. At 4 years old, Dog 44 is not vaccinated and loves to play in Ukraine.',
    images: [
      'https://images.dog.ceo/breeds/mastiff-english/1.jpg',
      'https://images.dog.ceo/breeds/mastiff-english/1_1.jpg',
      'https://images.dog.ceo/breeds/mastiff-english/1_2.jpg',
    ],
    name: 'Dog 44',
  },
  {
    location: 'Ukraine',
    isDog: true,
    sex: 'male',
    age: 5,
    type: 'Komondor',
    color: 'Mixed',
    isVaccinated: true,
    description:
      'This is a beautiful example of a Komondor, known for its Mixed coat. At 5 years old, Dog 45 is vaccinated and loves to play in Ukraine.',
    images: [
      'https://images.dog.ceo/breeds/komondor/n02105505_3713.jpg',
      'https://images.dog.ceo/breeds/komondor/n02105505_3713_1.jpg',
      'https://images.dog.ceo/breeds/komondor/n02105505_3713_2.jpg',
    ],
    name: 'Dog 45',
  },
  {
    location: 'Ukraine',
    isDog: true,
    sex: 'female',
    age: 6,
    type: 'Poodle Toy',
    color: 'Mixed',
    isVaccinated: false,
    description:
      'This is a beautiful example of a Poodle Toy, known for its Mixed coat. At 6 years old, Dog 46 is not vaccinated and loves to play in Ukraine.',
    images: [
      'https://images.dog.ceo/breeds/poodle-toy/n02113624_4589.jpg',
      'https://images.dog.ceo/breeds/poodle-toy/n02113624_4589_1.jpg',
      'https://images.dog.ceo/breeds/poodle-toy/n02113624_4589_2.jpg',
    ],
    name: 'Dog 46',
  },
  {
    location: 'Ukraine',
    isDog: true,
    sex: 'male',
    age: 7,
    type: 'Retriever Flatcoated',
    color: 'Mixed',
    isVaccinated: true,
    description:
      'This is a beautiful example of a Retriever Flatcoated, known for its Mixed coat. At 7 years old, Dog 47 is vaccinated and loves to play in Ukraine.',
    images: [
      'https://images.dog.ceo/breeds/retriever-flatcoated/n02099267_3768.jpg',
      'https://images.dog.ceo/breeds/retriever-flatcoated/n02099267_3768_1.jpg',
      'https://images.dog.ceo/breeds/retriever-flatcoated/n02099267_3768_2.jpg',
    ],
    name: 'Dog 47',
  },
  {
    location: 'Ukraine',
    isDog: true,
    sex: 'female',
    age: 8,
    type: 'Papillon',
    color: 'Mixed',
    isVaccinated: false,
    description:
      'This is a beautiful example of a Papillon, known for its Mixed coat. At 8 years old, Dog 48 is not vaccinated and loves to play in Ukraine.',
    images: [
      'https://images.dog.ceo/breeds/papillon/n02086910_3769.jpg',
      'https://images.dog.ceo/breeds/papillon/n02086910_3769_1.jpg',
      'https://images.dog.ceo/breeds/papillon/n02086910_3769_2.jpg',
    ],
    name: 'Dog 48',
  },
  {
    location: 'Ukraine',
    isDog: true,
    sex: 'male',
    age: 9,
    type: 'Mastiff English',
    color: 'Mixed',
    isVaccinated: true,
    description:
      'This is a beautiful example of a Mastiff English, known for its Mixed coat. At 9 years old, Dog 49 is vaccinated and loves to play in Ukraine.',
    images: [
      'https://images.dog.ceo/breeds/springer-english/n02102040_1983.jpg',
      'https://images.dog.ceo/breeds/springer-english/n02102040_2481.jpg',
      'https://images.dog.ceo/breeds/springer-english/n02102040_3335.jpg',
      'https://images.dog.ceo/breeds/springer-english/n02102040_3693.jpg',
      'https://images.dog.ceo/breeds/springer-english/n02102040_3974.jpg',
    ],
    name: 'Dog 49',
  },
  {
    location: 'Ukraine',
    isDog: true,
    sex: 'female',
    age: 10,
    type: 'Komondor',
    color: 'Mixed',
    isVaccinated: false,
    description:
      'This is a beautiful example of a Komondor, known for its Mixed coat. At 10 years old, Dog 50 is not vaccinated and loves to play in Ukraine.',
    images: [
      'https://images.dog.ceo/breeds/basenji/n02110806_4302.jpg',
      'https://images.dog.ceo/breeds/basenji/n02110806_4488.jpg',
    ],
    name: 'Dog 50',
  },
];
